version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: python-app
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql://user:password@db:5432/transactions
    command: tail -f /dev/null

volumes:
  postgres_data: